---
title: "L2T Database Explorer"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
params: 
  shiny_active: true
---

```{r setup, include = FALSE}
library(flexdashboard)
library(dplyr)
library(shiny)
library(L2TDatabase)
l2t <- l2t_connect(cnf_file = "./l2t_db.cnf")

query_set <- list(
  TimePoint1 = "q_Scores_TimePoint1", 
  TimePoint2 = "q_Scores_TimePoint2", 
  TimePoint3 = "q_Scores_TimePoint3")

prepare_study_query <- function(db, query_name) {
  tbl(db, query_name) %>% 
    collect %>% 
    mutate(DateCompiled = format(Sys.Date())) %>% 
    select(Study, DateCompiled, everything()) %>% 
    select(-ChildStudyID)
}


if (interactive() & !params$shiny_active) {
  input <- list()
  output <- list()
  input$tableChoice <- names(query_set)[1]

  dataset <- function() prepare_study_query(l2t, query_set[[input$tableChoice]])
}
```


Participant Data {data-orientation=rows}
======================================================================

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

View summary data for studies in the database.

```{r}
selectInput("tableChoice", "Study:", names(query_set))

dataset <- reactive({
  req(input$tableChoice)
  query <- query_set[[input$tableChoice]]
  prepare_study_query(l2t, query)
})

output$downloadStudyData <- downloadHandler(
    filename = function() {
      req(input$tableChoice)
      date_compiled <- format(Sys.Date())
      paste0(date_compiled, "_", input$tableChoice, ".csv")
    },            
    content = function(file) {
      req(dataset)
      readr::write_csv(dataset(), file)
    }
)
```

```{r}
renderUI(downloadButton("downloadStudyData"))
```


Tables
----------------------------------------------

```{r}
renderTable(dataset())
```



