---
title: "L2T Database Explorer"
resource_files:
- data/tp1.csv
- data/tp2.csv
- data/tp3.csv
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: lumen
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(flexdashboard)
library(shiny)
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

session$onSessionEnded(stopApp)

# App is in a subfolder of an RStudio project, unless it's running in
# ShinyApps.io, so look for Rproj or fail with "./"
find_app_dir <- function() {
  dir_proj <- rprojroot::find_root(rprojroot::is_rstudio_project)
  file.path(dir_proj, "app")
}

dir_app <- purrr::possibly(find_app_dir, ".", quiet = TRUE)()
source(file.path(dir_app, "helpers.R"))

# Here is where we would download stuff from the database but just work with the
# local files for the demo...

downloaded_queries <- list(
  TimePoint1 = readr::read_csv(file.path(dir_app, "data", "tp1.csv")),
  TimePoint2 = readr::read_csv(file.path(dir_app, "data", "tp2.csv")),
  TimePoint3 = readr::read_csv(file.path(dir_app, "data", "tp3.csv"))
)

downloaded_queries <- downloaded_queries %>%
  lapply(. %>% mutate(DateCompiled = format(Sys.Date())))

# Make a wide data-frame of all the longitudinal scores
remove_longitudinal_nondata_cols <- . %>%
  select(everything(), -ends_with("Completion"), -ends_with("Form"),
         -ends_with("Experiment"), -DateCompiled)

id_cols <- c("Study", "ResearchID", "Female", "AAE", "LateTalker", "CImplant")

fct_undummy_code <- function(x, labels) {
  factor(x, levels = c("0", "1"), labels = labels, exclude = NULL)
}

reshape_longitudinal_data <- . %>%
  tidyr::gather(Measure, Value, -one_of(id_cols)) %>%
  mutate(Study = stringr::str_replace(Study, "TimePoint", "T")) %>%
  tidyr::unite(Measure, Study, Measure)

long_comp <- downloaded_queries %>%
  lapply(remove_longitudinal_nondata_cols) %>%
  lapply(reshape_longitudinal_data) %>%
  bind_rows() %>%
  tidyr::spread(Measure, Value)

long_comp <- long_comp %>%
  readr::type_convert() %>%
  mutate(Female = fct_undummy_code(Female, c("Male", "Female")),
         AAE = fct_undummy_code(AAE, c("SAE", "AAE")),
         LateTalker = fct_undummy_code(LateTalker, c("TD", "Late Talker")),
         CImplant = fct_undummy_code(CImplant, c("TD", "C. Implant")))
```



About {data-orientation=rows}
===============================================================================

Row {data-height=400}
-----------------------------------------------------------------------

### About the app

[This app](https://github.com/tjmahr/l2t-database-explorer-demo) is a Shiny 
dashboard designed to provide interactive plotting of data from a three-year
longitudinal study of language development. I'll probably add more widgets over
time, but for now the main functionality is a page for interactive plotting,
model-fitting and descriptive statistics.

The real version of the app collects the data from a remote MySQL database, but
for the demo we are working with locally stored data. The data here are the
first 50 rows of each database query and uses only a third of the overall
columns. All numerical variables have been jittered, twice. This is just a demo
after all.

[Tristan Mahr](https://tjmahr.github.io/)


### About the measures 

The EVT is an expressive vocabulary test, PPVT a receptive vocabulary test, GFTA
an articulation test, Verbal Fluency how many words a child named in a
fluency retrival task, and LENA AWC the average number of words per hour
spoken to the child during a day-long LENA recording.


Participant Data {data-orientation=rows}
======================================================================

Inputs {.sidebar data-width=300}
-----------------------------------------------------------------------

View summary data for studies in the database.
 
```{r select-query}
selectInput("tableChoice", "Study:", names(downloaded_queries))  
```

```{r make-data-set}
dataset <- reactive({
  req(input$tableChoice)
  downloaded_queries[[input$tableChoice]]
})

# renderTable(head(dataset()))
```


```{r make-download-button}
output$downloadStudyData <- downloadHandler(
    filename = function() {
      req(input$tableChoice)
      date_compiled <- format(Sys.Date())
      paste0(date_compiled, "_", input$tableChoice, ".csv")
    },
    content = function(file) {
      req(dataset)
      readr::write_csv(dataset(), file)
    }
)
renderUI({downloadButton("downloadStudyData")})
```

<br/>

```{r download-all-button}
output$downloadAllData <- downloadHandler(
    filename = function() {
      date_compiled <- format(Sys.Date())
      paste0(date_compiled, "_", "all_studies", ".csv")
    },
    content = function(file) {
      bind_rows(downloaded_queries) %>% 
        readr::write_excel_csv(file)
    }
)
renderUI({downloadButton("downloadAllData", label = "Download all data")})
```



Tables {data-width=300}
----------------------------------------------

### Table

```{r}
renderTable(dataset())
```


Longitudinal Plotter {data-orientation=rows}
======================================================================

<!-- This page was adapted from this example dashboard
     https://jjallaire.shinyapps.io/shiny-ggplot2-diamonds/ -->

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("xLongScatter", "X", names(long_comp), "T1_EVT_GSV")
selectInput("yLongScatter", "Y", names(long_comp), "T2_EVT_GSV")
selectInput("colorLongScatter", "Color", c("None", names(long_comp)))

checkboxInput("splitColorLongScatter", "Median-Split Color", value = FALSE)


selectInput("facetRowLongScatter", "Facet Row",
            c(None = ".", names(long_comp[sapply(long_comp, is.factor)])))
selectInput("facetColLongScatter", "Facet Column",
            c(None = ".", names(long_comp[sapply(long_comp, is.factor)])))

selectInput("smoothLongScatter", "Trend line", 
            c(None = "None", Linear = "lm", LOESS = "loess"))
```

Outputs
-----------------------------------------------------------------------

### Score Plotter

```{r}
# The dataset needs to be (temporarily) modified if median splits are requested,
# so make it reactive
long_scatter_data <- reactive({
  req(input$colorLongScatter)
  p_data <- long_comp
  
  # We should split if the box is checked, "None" is not selected, and color
  # variable is numeric
  can_split <- input$splitColorLongScatter && 
    input$colorLongScatter != "None" && 
    is.numeric(p_data[[input$colorLongScatter]])
  
  col_split <- character()
  
  # Create a column with the medium split data
  if (can_split) {
    col_split <- paste0(input$colorLongScatter, "_Split")
    p_data[[col_split]] <- p_data[[input$colorLongScatter]] %>% 
      ntile(2) %>% 
      factor(1:2, c("Bottom Half", "Top Half"), exclude = NULL)
  }
  
  list(
    data = p_data,
    split = can_split,
    split_var = col_split
  )
})

renderPlot({
  req(long_scatter_data)
  plot_info <- long_scatter_data()
  
  p <- ggplot(plot_info$data) + 
    aes_string(x = input$xLongScatter, y = input$yLongScatter) + 
    geom_point()
  
  # Handle color
  if (input$colorLongScatter != "None") { 
    col_string <- if (plot_info$split) { 
      plot_info$split_var
    } else { 
      input$colorLongScatter
    }
    p <- p + aes_string(color = col_string)
  }
  
  facets <- paste(input$facetRowLongScatter, "~", input$facetColLongScatter)
  
  if (facets != ". ~ .") { 
    p <- p + facet_grid(facets)
  }
  
  if (input$smoothLongScatter != "None") {
    p <- p + geom_smooth(method = input$smoothLongScatter)
  }

  print(p)
})
```

Supporting information
-----------------------------------------------------------------------

### Multiple Regression (Numeric Variables Scaled to Mean 0, SD 1)

```{r}
fit_plotted_model <- reactive({
  # Get list of strings of plotting aesthetics
  variables <- list(
    x = input$xLongScatter,
    y = input$yLongScatter, 
    color = input$colorLongScatter,
    f_col = input$facetColLongScatter,
    f_row = input$facetRowLongScatter)

  # Remove non-data values
  f_parts <- variables %>% 
    Filter(function(x) x != "None" && x != ".", .)
  f_cols <- f_parts
  
  # Scale numeric values
  scale_string <- function(x) sprintf("scale(%s)", x)
  
  non_factors <- long_comp[unlist(f_parts)] %>% 
    sapply(is.numeric) %>% 
    which()
  
  f_parts[non_factors] <- f_parts[non_factors] %>% lapply(scale_string)

  # Combine predictors into a single interaction  
  f_pred <- f_parts[names(f_parts) != "y"]
  f_pred <- paste0(unlist(f_pred), collapse = " * ")
  
  # Combine response and predictor parts
  f_model <- paste0(f_parts$y, " ~ ", f_pred)
  model <- lm(f_model, long_comp)
  
  list(data = long_comp[unlist(f_cols)] %>% na.omit, 
       model = model)
})

renderPrint(arm::display(fit_plotted_model()[["model"]]))
```

### Descriptives {data-width=350}

```{r}
renderTable(fit_plotted_model()[["data"]] %>% 
              lapply(describe_col) %>% 
              bind_rows(.id = "Variable"))
```
